config:
  aws:region: us-east-1
  travel-app:keyPairName: travel-app-debug
  travel-app:openaiApiKey:
    secure: v1:a5bEUpgCaa5q+bb/:XkXNzpebvCrDI82wURktCwFE04I5ScLCinrPldhCkQdP9BWM6mAMqMy0B3Ww2cWx8EC1zJKc8bUu4mMWwK3k60hOXZdcHl8cAZDWsHxfBzPwebTc0BH0oT6v9d3sIVvPAdZE44qCKNwGWMHL2W2tmz8Yf4BLvD2dnGeHHj6c54LQQxZyRVbEVQWmNXC3RgFoot7O3SNFti4RYnzxrwZhbj6ZT6wWnspynibnARF9SJjnk1EJ
  travel-app:amadeusApiKey:
    secure: v1:EWdSI+YplKVF745b:uM39b/1c70oXmwJfTkKoxRjBxTpMI39oOeOGGp3eCbKhjpoUM6XuwmPmnvIUU3mc
  travel-app:amadeusApiSecret:
    secure: v1:1QVXpnnvWZReTl9c:l0+Pgdyh40/svA5rxnQR6et8tamaFkkpE5f232Zmn3I=
  travel-app:googleMapsApiKey:
    secure: v1:1kUEBtILVlr+wsBH:myApwpeOZNwBMNgKB9/h2RlFNeRgzpWVdEfwRyACgU6yM0EaXV2/smq8sq43/3UDSLu7iHG/3Q==
  travel-app:unsplashAccessKey:
    secure: v1:ioSUymSU5QNqZl/0:o7Ryuin4jrRyxBw1/eVo9PUUi63qRttudJj7ezvXRg7jVd+beMIH2pT5wKTGjhYxLyGbwf8I68qC2CM=
  travel-app:databaseUrl:
    secure: v1:o4o+TiKOqasVtIMU:dKneFca0OhU2pzljTgvOE2xA5cCWrHzQBL5vLLy8UIwphWkg0/Qu4rcOJV9KFOzum4AVybHJFMxpwpa92uNUMcf9e3BVTYOApFmsvbkQFdqduUK/2x95caJn1HG6QmNob99F3bUs2zM8YsC4uBZzSSxPwd+OJsII1JHep9EszY7Z3Q==
  travel-app:clerkPublishableKey:
    secure: v1:/0BWEBLaicefv/s5:ZKf1giB8dwGUhDgfIfvzW+4loe/bZP7cY/aNweTXMQDj8PTM2F8oJ3KwtqNMT/7FCD7o5ztFojMX+PA5OzGMKE+f5SLK6Y2R6XfpaPYZ
  travel-app:clerkSecretKey:
    secure: v1:UAb9PqgUusPKXaLe:xLYv0adGkfrnUWOeJxr6EYfMy1LgEax71tRiGJLzetC/Cfo95ue5C1iptiPBlPYthhq8uUrSC21rqCMQ3Wx9BD6K
encryptionsalt: v1:2TTctn3LIoE=:v1:+UEGmbdaqurwHXaw:H6/JY9EdVg02xhenAn5S+axCKSx3KA==
