"""
Tests for main.py FastAPI endpoints.

Uses httpx.AsyncClient + ASGI transport to test endpoints in-process
without needing a live server. Mocks the planner to avoid real API calls.

Covers:
  - GET / (health check)
  - POST /api/agentic/plan
  - POST /api/v1/agentic/generate-itinerary
  - POST /api/v1/agentic/generate-itinerary-stream (SSE)
  - POST /api/agentic/plan-stream (SSE)
  - GET /api/v1/cache/stats
  - GET /api/agentic/status/{run_id}
  - POST /api/v1/agentic/refine-itinerary
  - Validation errors (missing required fields)
"""
import json
import os
import sys
from unittest.mock import AsyncMock, patch, MagicMock

import pytest
import httpx

_service_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _service_root not in sys.path:
    sys.path.insert(0, _service_root)


@pytest.fixture(autouse=True)
def _reset_cache():
    import services.cache_service as cs
    cs._mem_cache = None
    cs._redis_client = None
    yield
    cs._mem_cache = None
    cs._redis_client = None


@pytest.fixture
def mock_planner_result(sample_itinerary_data):
    """Complete planner result dict."""
    return {
        "run_id": "test-run-123",
        "tour": {
            "city": "Paris",
            "country": "France",
            "title": "3-Day Paris Adventure",
            "description": "Amazing trip",
            "stops": sample_itinerary_data["top_10_places"],
            "daily_plans": sample_itinerary_data["daily_plans"],
            "daily_schedule": [],
            "recommended_hotels": sample_itinerary_data["recommended_hotels"],
            "compliance": sample_itinerary_data["compliance"],
            "research": {
                "highlights": sample_itinerary_data["highlights"],
                "local_tips": sample_itinerary_data["local_tips"],
                "estimated_costs": sample_itinerary_data["estimated_costs"],
            },
            "real_data": {"flights": [], "hotels": [], "has_real_data": False},
            "image": "https://source.unsplash.com/800x600/?travel,paris",
        },
        "cost": {"llm_tokens": 2000, "api_calls": 1, "total_usd": 0.01},
        "citations": ["Generated by AI"],
        "status": "completed",
    }


@pytest.fixture
def app_client(mock_planner_result):
    """
    httpx AsyncClient with the FastAPI app, planner mocked.
    """
    import main as main_module

    # Mock the planner
    mock_planner = MagicMock()
    mock_planner.generate_itinerary = AsyncMock(return_value=mock_planner_result)
    mock_planner.openai_client = MagicMock()
    
    # Mock streaming
    async def fake_stream(**kwargs):
        yield 'event: status\ndata: {"phase": "starting"}\n\n'
        yield 'event: chunk\ndata: {"text": "{"}\n\n'
        yield f'event: result\ndata: {json.dumps(mock_planner_result)}\n\n'
        yield 'event: done\ndata: {}\n\n'
    mock_planner.generate_itinerary_stream = fake_stream

    original_planner = main_module.planner
    main_module.planner = mock_planner

    client = httpx.AsyncClient(
        transport=httpx.ASGITransport(app=main_module.app),
        base_url="http://testserver",
    )

    yield client

    main_module.planner = original_planner


# ===================================================================
# Health check
# ===================================================================
class TestHealthCheck:
    @pytest.mark.asyncio
    async def test_root_returns_running(self, app_client):
        resp = await app_client.get("/")
        assert resp.status_code == 200
        data = resp.json()
        assert data["status"] == "running"
        assert data["service"] == "agentic-travel-planner"

    @pytest.mark.asyncio
    async def test_root_has_version(self, app_client):
        resp = await app_client.get("/")
        assert "version" in resp.json()


# ===================================================================
# GET /api/agentic/status/{run_id}
# ===================================================================
class TestStatusEndpoint:
    @pytest.mark.asyncio
    async def test_status_returns_completed(self, app_client):
        resp = await app_client.get("/api/agentic/status/some-run-id")
        assert resp.status_code == 200
        data = resp.json()
        assert data["run_id"] == "some-run-id"
        assert data["status"] == "completed"


# ===================================================================
# POST /api/agentic/plan
# ===================================================================
class TestPlanEndpoint:
    @pytest.mark.asyncio
    async def test_plan_success(self, app_client, sample_plan_request):
        resp = await app_client.post("/api/agentic/plan", json=sample_plan_request)
        assert resp.status_code == 200
        data = resp.json()
        assert data["status"] == "completed"
        assert data["run_id"] == "test-run-123"
        assert data["tour"]["city"] == "Paris"

    @pytest.mark.asyncio
    async def test_plan_missing_city(self, app_client):
        resp = await app_client.post("/api/agentic/plan", json={"country": "France"})
        assert resp.status_code == 422  # validation error

    @pytest.mark.asyncio
    async def test_plan_minimal_request(self, app_client):
        """city and country are the only required fields."""
        resp = await app_client.post("/api/agentic/plan", json={
            "city": "London", "country": "UK"
        })
        assert resp.status_code == 200

    @pytest.mark.asyncio
    async def test_plan_preferences_as_list(self, app_client):
        """preferences can be passed as a list."""
        resp = await app_client.post("/api/agentic/plan", json={
            "city": "Rome", "country": "Italy",
            "preferences": ["food", "history"],
        })
        assert resp.status_code == 200

    @pytest.mark.asyncio
    async def test_plan_planner_unavailable(self, app_client):
        """When planner is None, returns 503."""
        import main as main_module
        saved = main_module.planner
        main_module.planner = None
        try:
            resp = await app_client.post("/api/agentic/plan", json={
                "city": "Paris", "country": "France"
            })
            assert resp.status_code == 503
        finally:
            main_module.planner = saved


# ===================================================================
# POST /api/v1/agentic/generate-itinerary
# ===================================================================
class TestGenerateItineraryEndpoint:
    @pytest.mark.asyncio
    async def test_generate_success(self, app_client):
        resp = await app_client.post("/api/v1/agentic/generate-itinerary", json={
            "city": "Paris",
            "country": "France",
            "days": 3,
            "user_id": "test-user",
        })
        assert resp.status_code == 200
        data = resp.json()
        assert data["status"] == "completed"

    @pytest.mark.asyncio
    async def test_generate_with_preferences(self, app_client):
        resp = await app_client.post("/api/v1/agentic/generate-itinerary", json={
            "city": "Tokyo",
            "country": "Japan",
            "days": 5,
            "budget": 3000,
            "preferences": ["culture", "food"],
            "user_id": "test-user",
        })
        assert resp.status_code == 200

    @pytest.mark.asyncio
    async def test_generate_missing_user_id(self, app_client):
        """user_id is required for this endpoint."""
        resp = await app_client.post("/api/v1/agentic/generate-itinerary", json={
            "city": "Paris", "country": "France", "days": 3,
        })
        assert resp.status_code == 422

    @pytest.mark.asyncio
    async def test_generate_missing_city(self, app_client):
        resp = await app_client.post("/api/v1/agentic/generate-itinerary", json={
            "country": "France", "days": 3, "user_id": "u1",
        })
        assert resp.status_code == 422


# ===================================================================
# GET /api/v1/cache/stats
# ===================================================================
class TestCacheStatsEndpoint:
    @pytest.mark.asyncio
    async def test_cache_stats(self, app_client):
        resp = await app_client.get("/api/v1/cache/stats")
        assert resp.status_code == 200
        data = resp.json()
        assert "memory_size" in data
        assert "memory_maxsize" in data
        assert data["memory_maxsize"] == 512


# ===================================================================
# POST /api/v1/agentic/generate-itinerary-stream (SSE)
# ===================================================================
class TestStreamEndpoint:
    @pytest.mark.asyncio
    async def test_stream_returns_sse(self, app_client):
        resp = await app_client.post(
            "/api/v1/agentic/generate-itinerary-stream",
            json={
                "city": "Paris",
                "country": "France",
                "days": 3,
                "user_id": "test-user",
            },
        )
        assert resp.status_code == 200
        assert "text/event-stream" in resp.headers.get("content-type", "")

    @pytest.mark.asyncio
    async def test_stream_contains_events(self, app_client):
        resp = await app_client.post(
            "/api/v1/agentic/generate-itinerary-stream",
            json={
                "city": "Paris",
                "country": "France",
                "days": 3,
                "user_id": "test-user",
            },
        )
        body = resp.text
        assert "event: status" in body
        assert "event: done" in body

    @pytest.mark.asyncio
    async def test_stream_planner_unavailable(self, app_client):
        import main as main_module
        saved = main_module.planner
        main_module.planner = None
        try:
            resp = await app_client.post(
                "/api/v1/agentic/generate-itinerary-stream",
                json={"city": "Paris", "country": "France", "days": 3, "user_id": "u1"},
            )
            assert resp.status_code == 503
        finally:
            main_module.planner = saved


# ===================================================================
# POST /api/agentic/plan-stream (SSE)
# ===================================================================
class TestPlanStreamEndpoint:
    @pytest.mark.asyncio
    async def test_plan_stream_returns_sse(self, app_client):
        resp = await app_client.post(
            "/api/agentic/plan-stream",
            json={
                "city": "London",
                "country": "UK",
                "days": 2,
            },
        )
        assert resp.status_code == 200
        assert "text/event-stream" in resp.headers.get("content-type", "")

    @pytest.mark.asyncio
    async def test_plan_stream_contains_done(self, app_client):
        resp = await app_client.post(
            "/api/agentic/plan-stream",
            json={"city": "London", "country": "UK", "days": 2},
        )
        assert "event: done" in resp.text


# ===================================================================
# POST /api/v1/agentic/refine-itinerary
# ===================================================================
class TestRefineEndpoint:
    @pytest.mark.asyncio
    async def test_refine_planner_unavailable(self, app_client):
        import main as main_module
        saved = main_module.planner
        main_module.planner = None
        try:
            resp = await app_client.post("/api/v1/agentic/refine-itinerary", json={
                "run_id": "r1",
                "current_itinerary": {"title": "Test"},
                "refinement": "Add more museums",
                "user_id": "u1",
            })
            assert resp.status_code == 503
        finally:
            main_module.planner = saved

    @pytest.mark.asyncio
    async def test_refine_missing_fields(self, app_client):
        resp = await app_client.post("/api/v1/agentic/refine-itinerary", json={
            "run_id": "r1",
        })
        assert resp.status_code == 422


# ===================================================================
# Validation error handler
# ===================================================================
class TestValidationErrorHandler:
    @pytest.mark.asyncio
    async def test_422_returns_json(self, app_client):
        """Validation errors should return structured JSON, not HTML."""
        resp = await app_client.post("/api/agentic/plan", json={})
        assert resp.status_code == 422
        data = resp.json()
        assert "detail" in data
